[package]
name = "rnvim"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rnvim"
path = "src/main.rs"

[dependencies]
rnvim-proto.workspace = true
rnvim-agent.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
include_dir.workspace = true
base64.workspace = true
dialoguer = { version = "0.11", features = ["fuzzy-select"] }
portable-pty = "0.9"
libc = "0.2"

[dev-dependencies]
tempfile.workspace = true
